#	%W% (Berkeley) %G%
CC=gcc
PROG=sh
STUBS=	builtins cd dirent echo error eval exec expand \
input jobs mail main memalloc miscbltin \
mystring nodes options parser redir show signames \
syntax trap output var
OBJS= init.o $(addsuffix .o, $(STUBS))
SRCS=$(addsuffix .c, $(STUBS))
CFLAGS=-DSHELL -I.
CLEANFILES=builtins.c builtins.h init.c mkinit mknodes mksignames mksyntax \
nodes.c nodes.h signames.c signames.h syntax.c syntax.h token.def

sh: $(OBJS)
	$(CC) $(LDFLAGS) -o sh $(OBJS) $(LOADLIBES)

parser.o: token.def
	$(CC) $(CFLAGS) -c -o parser.o parser.c

token.def: mktokens
	sh mktokens

builtins.h builtins.c: mkbuiltins builtins.def
	sh mkbuiltins

init.c: mkinit $(SRCS)
	./mkinit '$(CC) -c $(CFLAGS) init.c' $(SRCS)

mkinit: mkinit.c
	$(CC) $(CFLAGS) mkinit.c -o $@

nodes.c nodes.h: mknodes nodetypes nodes.c.pat
	./mknodes nodetypes nodes.c.pat

mknodes: mknodes.c
	$(CC) $(CFLAGS) mknodes.c -o $@

signames.c signames.h: mksignames
	./mksignames

mksignames: mksignames.c
	$(CC) $(CFLAGS) mksignames.c -o $@

syntax.c syntax.h: mksyntax
	./mksyntax

mksyntax: mksyntax.c parser.h
	$(CC) $(CFLAGS) mksyntax.c -o $@
