#
# inetd.conf	This file describes the services that will be available
#		through the INETD TCP/IP super server.  To re-configure
#		the running INETD process, edit this file, then send the
#		INETD process a SIGHUP signal.
#
# Version:	@(#)/etc/inetd.conf	3.10	05/27/93
#
# Authors:	Original taken from BSD UNIX 4.3/TAHOE.
#		Fred N. van Kempen, <waltje@uwalt.nl.mugnet.org>
#		Kay Roemer <roemer@rbi.informatik.uni-frankfurt.de>
#
#
# <service_name> <sock_type> <proto> <flags> <user> <server_path> <args>
#
# Echo, discard, daytime, and chargen are used primarily for testing.
#
echo	stream	tcp	nowait	root	internal
echo	dgram	udp	wait	root	internal
discard	stream	tcp	nowait	root	internal
discard	dgram	udp	wait	root	internal
daytime	stream	tcp	nowait	root	internal
daytime	dgram	udp	wait	root	internal
chargen	stream	tcp	nowait	root	internal
chargen	dgram	udp	wait	root	internal
#
#
# RPC services.
#
#mountd/1	dgram	rpc/udp	wait	root	/usr/etc/rpc.mountd rpc.mountd
#rstatd/1	dgram	rpc/udp	wait	root	/usr/etc/rpc.rstatd rpc.rstatd
#
# These are standard services.
#
ftp	stream	tcp	nowait	root	/usr/etc/in.ftpd	in.ftpd
telnet	stream  tcp     nowait  root    /usr/etc/in.telnetd	in.telnetd
#smtp	stream  tcp     nowait  root    /usr/lib/umail		/usr/lib/umail -bS
#nntp	stream	tcp	nowait	root	/usr/etc/in.nntpd	in.nntpd
#
# Shell, login, exec and talk are BSD protocols.
#
shell	stream	tcp	nowait	root	/usr/etc/in.rshd	in.rshd
login	stream	tcp	nowait	root	/usr/etc/in.rlogind	in.rlogind
exec	stream	tcp	nowait	root	/usr/etc/in.rexecd	in.rexecd
talk	dgram	udp	wait	root	/usr/etc/in.ntalkd	in.ntalkd
ntalk	dgram	udp	wait	root	/usr/etc/in.ntalkd	in.ntalkd
#
# Pop et al
#
#pop-2	stream	tcp	nowait	root	/usr/etc/in.popd	in.popd
#pop-3	stream	tcp	nowait	root	/usr/etc/in.popd	in.popd
#
# The Internet UUCP service.
#
#uucp	stream	tcp	nowait	uucp	/usr/lib/uucp/uucico	/usr/lib/uucp/uucico -l
#
# Tftp service is provided primarily for booting.  Most sites
# run this only on machines acting as "boot servers." 
#
tftp	dgram	udp	wait	root	/usr/etc/in.tftpd	in.tftpd -s /tftpboot
#bootps	dgram	udp	wait	root	/usr/etc/in.bootpd	in.bootpd
#
# Finger, systat and netstat give out user information which may be
# valuable to potential "system crackers."  Many sites choose to disable 
# some or all of these services to improve security.
#
finger	stream	tcp	nowait	root	/usr/etc/in.fingerd	in.fingerd
#systat	stream	tcp	nowait	guest	/usr/bin/ps	/usr/bin/ps -auwwx
#netstat stream	tcp	nowait	guest	/bin/netstat	/bin/netstat -f inet
#
# Time service is used for clock syncronization.
#
#time	stream	tcp	nowait	root	/usr/etc/in.timed	in.timed
#time	dgram	udp	wait	root	/usr/etc/in.timed	in.timed
#
# End of inetd.conf.
